# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Pay-As-You-Go (66c03438-90ae-4c3a-a56e-085514c2d9a2)'
    subscriptionId: '66c03438-90ae-4c3a-a56e-085514c2d9a2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'StudyAnyTimeResourceGroup'
    location: 'Australia Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/CredibleAshok/TestRepoForAzureResourceDeployment/main/CreateWebApp/azuredeploy.json'
    deploymentMode: 'Incremental'
